### PR TITLE
Fix/zerofill anonymous pages

### PR DESCRIPTION
**Pull request by m1ghtym0**
Solves this issue:
https://github.com/angr/angr-doc/blob/master/examples/simple_heap_overflow/solve.py#L26

### CODE REVIEW

**Comment by zardus** [comment]
As mentioned on slack, could you rebase this onto `r/trees`? I hate to do that to you, but it's the future!

**Comment by Lukas-Dresel** [comment]
Please see my comments on #126, they might apply here too

**Comment by zardus** [comment]
This is superceded by #126, right?

**Comment by m1ghtym0** [comment]
Basically yes, this is the same fix applied on the master branch, if you'll merge r/trees anyways, this
is redundant.

**Pull request closed without merging**
