### PR TITLE
Add support for arch_prctl syscall

### PR DESCRIPTION
**Pull request by sam-b**
I think this should fix https://github.com/angr/angr/issues/127 I'm not entirely sure on the handling of errors (the other syscall implementations don't seem to return any error codes?) or what any tests for this should look like though?

### CODE REVIEW

**Comment by rhelmot** [comment]
This will not work. You're doing `if parameter == value:`, which won't work because the parameters to SimProcedures are bitvectors, and performing equality checks on bitvectors will return a symbolic boolean, and you can't check the truthiness of a symbolic boolean!

The easy fix would be to just error out if the parameter is symbolic, then convert it to a python int with `self.state.any_int(x)`

**Comment by zardus** [comment]
This isn't the place for it, but as an internal note-to-us: we might want to look at using the global conditional support I implemented at some point (https://github.com/angr/simuvex/blob/master/simuvex/s_state.py#L651). Using that, this code would be something like:

```
    #ARCH_SET_GS
    with self.state.with_condition(code == 0x1001): 
         self.regs.gs = addr

     #ARCH_SET_FS
     with self.state.with_condition(code == 0x1002):
         self.regs.fs = addr

     #ARCH_GET_FS
     with self.state.with_condition(code == 0x1003):
         fs = self.regs.fs
         self.state.memory.store(addr,fs)

     #ARCH_GET_GS
     with self.state.with_condition(code == 0x1004):
         gs = self.regs.gs
         self.state.memory.store(addr,gs)
```

The global condition stuff isn't yet used anywhere else, so this might be rather adventurous ;-)

**Comment by sam-b** [comment]
Updated the pull request with a symbolic check + conversion

**Comment by ltfish** [comment]
Can someone take care of this PR and the related one (https://github.com/angr/angr/pull/178)?

**Comment by rhelmot** [comment]
@sam-b sorry for not catching this earlier, but could you change `raise Exception` to either `raise SimValueError` or, preferable, return an error code from the simprocedure? raising the default exception is really bad because it can happen during normal analyses and we only catch exceptions that subclass the angr errors.

**Comment by sam-b** [comment]
Hey - sorry for the slow response, the weekend was more hectic then planned. I'm cramming for an exam atm but I'll fix this up Thursday once I'm free.

**Comment by sam-b** [comment]
@rhelmot updated - let me know if it's reasonable.

**Comment by rhelmot** [comment]
Thank you! I'm really sorry this took such a long time to go through, I have been traveling a lot and getting ready for the new school year.

**Pull request merged**
