### PR TITLE
Udating mmap syscall

### PR DESCRIPTION
**Pull request by Owlz**
Couple things going on here.

1 -- Outputting warning if we're truncating mmap area
2 -- mmap was assuming that the addr field was always NULL. If a binary requested a specific address and then checked that address (such as UPX), it would simply exit out.

Questions
1 -- The any_int call for size... Should it really be *8?

2 -- I found out why my malloc tracing sometimes fails. malloc will sometimes use mmap instead of brk. In this case, it will also use ANONYMOUS flag for the memory, which POSIX says should be initialized to 0. Since angr isn't doing that, it's causing unncessary forks in execution. The problem here is I don't know a good way to constrain/underconstrain it so that it doesn't have the initialization overhead. CGC_ZEROFILL thing works great, but I think we want to be able to apply that thought process on the memory page level so things like ANONYMOUS mmap won't bog the system down.

3-- There should likely be errors somehow returned from the map_region call if the page is already in use. Not sure how you guys would like to pass those messages, but mmap should watch for them and return -1 if, for instance, the page was already taken.

### CODE REVIEW

**Comment by ltfish** [comment]
> The any_int call for size... Should it really be *8?

No. `* 8` is a bug.

> ... CGC_ZEROFILL thing works great, but I think we want to be able to apply that thought process on the memory page level so things like ANONYMOUS mmap won't bog the system down.

I agree. It should be an option put into `SimPagedMemory`. @zardus How's your paged memory code? Do you mind me implementing this support without merging your branch?

> There should likely be errors somehow returned from the map_region call if the page is already in use. 

Umm can you please elaborate on "page is in use"?

**Comment by Owlz** [comment]
No problems here if it's easier for you to implement and merge your own branch.

The error I'm mentioning is that, since this merge adds the ability for the mmap caller to specify a source address, sometimes that source address is already in use. It's not a normal case, but it's certainly possible for an mmap call to try to map into, say the .text area. In that case, I believe the appropriate action is for mmap to actually return -1 (and set errno).

The problem here is, that check is implicitly being done in the mem.map_region call. It will send an error to the screen, but the mmap syscall has no way of knowing that the error occurred. The net effect would be possibly returning a pointer to an already mapped area when the return should instead be -1.

**Comment by ltfish** [comment]
> In that case, I believe the appropriate action is for mmap to actually return -1 (and set errno).

It only happens if both `addr` and `MAP_FIXED` is specified. You may add a check and return a `-1` in that case. You'll have to modify `SimMemory.map_region()`. Raising an exception there, and you can catch it in `mmap()` implementation.

**Comment by Owlz** [comment]
So i think i got those changed done. Let me know what you guys want to do about the MAP_ANONYMOUS 0 initialization on pages.

**Comment by ltfish** [comment]
> Let me know what you guys want to do about the MAP_ANONYMOUS 0 initialization on pages.

I'll merge the current PR, and then implement the zero-filled pages support later on master branch. Thanks!

**Pull request merged**
