### PR TITLE
Add _op_Iop_QNarrowBin16Sto8Ux16 for PACKUSWB xmm1, xmm2

### PR DESCRIPTION
**Pull request by SlivTaMere**
This only adds support for the PACKUSWB instruction with two 128 bits operands but there is a generic function for other versions of PACKUSWB (and maybe other stuff).

Edit: actually supports also VPACKUSWB xmm1, xmm2, xmm3 (basically the same instruction)

### CODE REVIEW

**Comment by zardus** [comment]
As simuvex is currently being merged into angr, would you mind instead making this PR to the `wip/the_end_times` branch of angr (https://github.com/angr/angr/tree/wip/the_end_times)? That'll make things much easier for us!

**Comment by SlivTaMere** [comment]
Sure! I'm seeing build fails in Travis Cl, I'll fix that too.

**Comment by zardus** [comment]
It might be worth making the tests pass on here before moving it over to `wip/the_end_times`. That branch is not fully functional yet, so tests won't pass anyways :-)

**Comment by rhelmot** [comment]
Hi, I just noticed that your implementation of `saturate` will fail given symbolic values. The comparison will generate a symbolic condition and claripy will throw an exception from being asked to convert a symbolic condition to a concrete one implicitly. Could you rewrite that method with if-then-else trees?

**Comment by SlivTaMere** [comment]
Build fail at https://travis-ci.org/angr/simuvex/jobs/250119502#L1522 . No idea how is it related to my commits.

**Comment by rhelmot** [comment]
That error may be ignored.

**Comment by zardus** [comment]
Closing, as this was merged on angr. Thanks!

**Pull request closed without merging**
