### PR TITLE
Update comments and reformatting.

### PR DESCRIPTION
**Pull request by ekse**
Mostly reformatting, the only added content is the definition of IMark (did I get it right?).

Also, PEP8 recommends 2 white lines before class definitions. If we would rather keep the formatting as it is I can modify my code style config so that it stops complaining about it.

### CODE REVIEW

**Comment by rhelmot** [comment]
Thanks! Your IMark description is precisely correct.

**Comment by zardus** [comment]
Regarding the lines before the class definition, what style checker are you using? We use pylint (which I guess isn't really just a style checker), with the configuration in `angr-dev` (https://github.com/angr/angr-dev/blob/master/pylintrc). In theory, that file should produce a clean lint on all the repos. In practice, some people don't use it and end up pushing code that doesn't lint :-(

I'm personally pretty happy with that pylintrc, but I'm open to slowly changing to be more pep8-like in some ways (like the line skip before classes) if it makes life easier for people. We also have a dream of one day cleaning up the linting errors and making linting part of the CI to maintain future code quality.

**Comment by ekse** [comment]
I'm using PyCharm which highlights PEP8 discrepancies by default. I don't really have a preference, I made the change while I was editing those files as the contributing page recommends following PEP8. 

I have become used to always have clang-format cleaning up formatting at work before committing which makes formatting a non-issue. I see that Google released a python formatting tool, I have not tried it though.

https://github.com/google/yapf

**Comment by salls** [comment]
I'm in favor of using PEP8

**Comment by zardus** [comment]
I actually really like that formatter idea! We should look into it further.
Setting that up as a pre-commit hook or something could be really cool.

**Comment by ekse** [comment]
I can give yapf a spin, see what the workflow could look like.

**Comment by ltfish** [comment]
yapf seems to be too aggressive for us. We can first enable pylint in CI and see how that goes.

**Comment by rhelmot** [comment]
Enabling pylint in CI will cause every build between now and next year, when we finally fix linting, to fail.

**Comment by ekse** [comment]
Oops, I think I just opened a can of worms :P I'll let you debate internally what you think is needed.

**Pull request merged**
