### PR TITLE
Fixed a typo in the armg_calculate_flag_c helper function

### PR DESCRIPTION
**Pull request by iamahuman**
This one might have been somewhat hard to find, since this is usually triggered only when doing things like doing 64-bit integer addition / subtraction with a pair of `add / adc` or `sub / sbc` instructions. You may compare this with https://github.com/angr/vex/blob/master/priv/guest_x86_defs.h.

### CODE REVIEW

**Comment by ltfish** [comment]
This is a legit fix! Thank you!

We will get to it once our internal development branch is merged to master.

**Comment by ltfish** [comment]
@iamahuman Obviously we made quite a lot of changes, and `simuvex/vex/ccall.py` is moved to `simuvex/engines/vex/ccall.py`. Can you please rebase your changes and make a new push, so we can merge in this PR? Sorry about that.

**Comment by iamahuman** [comment]
@ltfish No worries. Here you go ;)

**Comment by zardus** [comment]
The failing testcase in this one is a known issue. Merging this in!

**Pull request merged**
