### PR TITLE
Implement SimSockets by having 2 SimFiles for send/recv

### PR DESCRIPTION
**Pull request by ctfhacker**
Replace each socket fd with 2 SimFiles, one for send and one for recv.

`posix.sockets` still contains a list of current sockets
`posix.dumps` now can take a `SimSocket` and returns a `SocketResult` namedtuple that contains the results of concretizing the two SimFiles for the socket.

i.e.

```
for socket_fd, curr_socket in f.state.posix.sockets.iteritems():
    result = f.state.posix.dumps(curr_socket)
    # result.send contains concretized send
    # result.recv contains concretized recv
```

There is also a test case for sockets included as well.

### CODE REVIEW

**Comment by zardus** [comment]
So we're in the process of getting our binaries repo on github. When this happens, would you mind moving the testcase binaries there and moving the testcases that use angr to the angr repo? Should be later today; I'll give you another ping when it's ready.

**Comment by ctfhacker** [comment]
I would have no problems at all with that. Should I simply remove the test cases with this PR?

**Comment by zardus** [comment]
Hey! Really sorry for the delay on this. When I get super busy, I start packet dropping, and this packet got dropped.

I pushed the binaries repo: https://github.com/angr/binaries. Could you put the binaries in that repo, and the testcases that use angr in the angr repo?

Thanks for the contribution!

**Comment by ctfhacker** [comment]
Moved the binaries and test suite to the right repos... i think..

**Comment by ctfhacker** [comment]
Ok, how does this look? ;-)

**Comment by zardus** [comment]
Hey! Just letting you know we haven't forgotten about this -- there's a big conference deadline coming up and we're all working furiously, but I'll get to this next Friday!

**Comment by ltfish** [comment]
@zardus ping!

**Comment by zardus** [comment]
Sorry, this PR totally fell through the cracks last Usenix deadline.

Looking over it again, I am a bit concerned that `state.posix.dumps` can return two different types -- a string (for files), and a namedtuple (for sockets). I don't have a good solution, but I'd like to avoid this sort of type mixing.

In general, we might take this opportunity to do the "dialog refactor" that we've always wanted to get to -- unifying files and sockets in a more generic SimStream or something?

**Comment by zardus** [comment]
Now that simuvex has been merged into angr, I'm going to close this PR. This should be much easier on the new angr, but we should do the work in the angr repo.

Thanks!

**Pull request closed without merging**
