### PR TITLE
added uname syscall handler

### PR DESCRIPTION
**Pull request by stef**

### CODE REVIEW

**Comment by stef** [comment]
i'm not quite sure what check failed in the travis build

**Comment by ekilmer** [comment]
@stef It looks like a linting failure:
```
LINT FAILURE: new file simuvex/procedures/syscalls/uname.py lints at 8.46/10.00. Errors:
C: 28, 0: Trailing newlines (trailing-newlines)
W:  7, 4: Arguments number differs from overridden 'run' method (arguments-differ)
```
You can run something like this on the files you've changed to make sure that they pass the linting before you commit by running `pylint --rcfile=~/src/angr-dev/pylintrc uname.py`. You can find pylintrc [here](https://github.com/angr/angr-dev/blob/master/pylintrc) and `pylint` can be installed through `apt-get`

**Comment by rhelmot** [comment]
that particular error is gonna happen when you write a simprocedure, so it's safe to disable it by putting `# pylint: disable=arguments-differ` at the top of the file. The other one, though, is something you should just fix by removing the trailing newlines :)

**Comment by stef** [comment]
fixed the pylint stuff, also made the uname strings 65 bytes long as per reality.

**Comment by ltfish** [comment]
The code looks good to me. Thank you!

**Comment by stef** [comment]
actually i  figured out that the return value being 64 bit only works on 64 bit obviously, when i do the same on 32 bit i need to return a 32bit zero, how do i do this in general, correctly?

**Comment by ltfish** [comment]
> actually i figured out that the return value being 64 bit only works on 64 bit obviously, when i do the same on 32 bit i need to return a 32bit zero, how do i do this in general, correctly?

Ouch I didn't catch that. You can just do `return 0`.

**Comment by ltfish** [comment]
Alternatively you can take the bits from `self.state.arch.bits`. It's 32 for 32-bit platforms and 64 for 64-bit platforms.

**Pull request merged**
