### PR TITLE
Implement pc_actions_ROL and corresponding tests in test_vex.py

### PR DESCRIPTION
**Pull request by extremecoders-re**
This PR implements the function `pc_actions_ROL` in `simuvex/vex/ccall.py` and the corresponding tests in function  `test_ccall()` in file `test_vex.py`

### CODE REVIEW

**Comment by zardus** [comment]
Hello,

This PR fails the build with:

```
======================================================================
ERROR: test_vex.test_ccall
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/angr/.virtualenvs/angr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/angr/angr/simuvex/tests/test_vex.py", line 63, in test_ccall
    cf, pf, af, zf, sf, of = s_ccall.pc_actions_ROL(s, 8, arg_l, arg_r, 0, platform='AMD64')
  File "/home/angr/angr/simuvex/simuvex/vex/ccall.py", line 377, in pc_actions_ROL
    pf = (cc_ndep & data[platform]['CondBitMasks']['G_CC_MASK_P'])[data[platform]['CondBitOffsets']['G_CC_SHIFT_P']]
TypeError: 'int' object has no attribute '__getitem__'
```

I think it's actually a matter of the testcase pushing ints, which won't happen in normal operation (they'll be `BV`s, instead. Would you mind fixing the testcase?

**Comment by extremecoders-re** [comment]
Done. The cc_ndep argument is changed to BitVector.

**Comment by zardus** [comment]
All the tests pass! Would you mind squashing the commits into one solid one, like in the angr PR?

Thank you for these PRs!

**Comment by extremecoders-re** [comment]
Done. :-)
Is that all for this PR.

**Comment by extremecoders-re** [comment]
This is causing problems. :-(
Can you discard this PR? 
I would like to start afresh with a new PR from the current clone.

**Pull request closed without merging**
